### ISSUE TITLE
Version 8.0.6 is not available on NPM?

### ISSUE THREAD

**Issue by chuckdries** [sergeysova/styled-normalize#11]
https://www.npmjs.com/package/styled-normalize is only showing 8.0.4, and `yarn add` installs 8.0.4, which has broken types. I had to install from git, which is totally fine, but you should probably publish the most recent version

**Comment by sergeysova** [comment]
Hello! Install next version please.

https://www.npmjs.com/package/styled-normalize Open Versions tab

**Comment by chuckdries** [comment]
Ah! apologies for my ignorance. Out of curiosity, why does prev-latest-next go 5-4-6 in this case?

**Comment by sergeysova** [comment]
@chuckdries I updated tags. Now `latest` is `8.0.6`
