### ISSUE TITLE
@prev tag still requires styled-components >4

### ISSUE THREAD

**Issue by lauriejones** [sergeysova/styled-normalize#12]
I am still on version 3 of styled components and your docs instruct us to install using the `@prev` tag, so I did. 

`8.0.5` is the version that is installed when running `npm i styled-normalize@prev`, but it is not compatible with SC v3.

This version does work: `npm i styled-normalize@8.0.5-prev` and should be tagged as the latest `prev` version.

Thanks!

**Comment by sergeysova** [comment]
@lauriejones Thank you.

Now fixed:

![image](https://user-images.githubusercontent.com/5620073/55950031-9fd82500-5c5c-11e9-9344-fb1ad84210c6.png)

**Comment by lauriejones** [comment]
Thank you!
