### ISSUE TITLE
Require more examples of setup

### ISSUE THREAD

**Issue by khanzzirfan** [sergeysova/styled-normalize#14]
Hi, 
Just finding it hard to understand how to import styled-normalize and combine it together with `createGlobalStyle`. Readme is not good enough to understand, specifically the below code

```
// ES Modules
import { normalize, Normalize } from 'styled-normalize'

// CommonJS
const { normalize, Normalize } = require('styled-normalize')

createGlobalStyle` ${normalize} `
<Normalize />
```

What is  the last line <Normalize> means? Are you exporting the component ?

It would helpful if there is sample app to see how it works with Styled-Component V4. 

your help is really appreciated.

Thanks

**Comment by sergeysova** [comment]
@sahilkhan99 Hello. Please, check.
https://github.com/sergeysova/styled-normalize/blob/master/README.md

Is it better?

**Comment by khanzzirfan** [comment]
Apologies for late reply!. Its way better to understand now. Thank you for all the efforts.
