### ISSUE TITLE
Why is the version a "const" ?

### ISSUE THREAD

**Issue by yairEO** [sergeysova/styled-normalize#5]
Never seen that before. 
Any reason why it's not written as a comment at the top of the file?

**Comment by sergeysova** [comment]
One app requires, to show the version of normalize.css used.
Also, some developers check the version of normalize in their code.

**Comment by yairEO** [comment]
so why aren't any of the million other NPM packages doing it? 
I just don't see any reason at all. if anyone wants to actively check the version in their code they can parse the package.json file, no need to pollute each script on the plant with a variable specifying its version.

**Comment by sergeysova** [comment]
You're right. But in previous releases version of styled-normalize was differed from the version of normalize.css

**Comment by sergeysova** [comment]
I'm going to remove `version` export in `v8.0.4` (#9)

**Comment by sergeysova** [comment]
https://github.com/sergeysova/styled-normalize/releases/tag/v8.0.4
