### ISSUE TITLE
styled-normalize@8.0.3 types are incompatible with styled-components@<4

### ISSUE THREAD

**Issue by elektronik2k5** [sergeysova/styled-normalize#9]
Hello and thanks for creating this package! :bowing_man: 

I tried upgrading styled-normalize from `8.0.2` to `8.0.3` with the latest `styled-components@3`. Because https://github.com/sergeysova/styled-normalize/blob/bb1b9e1296be41980e51fb00cb66dd02fa675c2e/index.d.ts#L1 imports `styled-components@4`'s `GlobalStyleClass, DefaultTheme`, which don't exist in v3 - TS compilation fails.

I don't really see a way around this, except for fixing peerDependencies to exclude `styled-components@4` in `styled-normalize@>=8.0.3`.

I think this also warrants a new major version and unpublishing of `styled-normalize@8.0.3`, since it's broken for TS users.

**Comment by sergeysova** [comment]
@elektronik2k5 Thank you.
styled-normalize not follows semver. Version x.y matches normalize.css https://github.com/sergeysova/styled-normalize/releases/tag/v8.0.0.

I'm going to release patch version with the fix (`8.0.4`)

**Comment by sergeysova** [comment]
@elektronik2k5 Please, use https://github.com/sergeysova/styled-normalize/releases/tag/v8.0.4

```bash
npm install styled-normalize@next
```

**Comment by sergeysova** [comment]
@elektronik2k5 If you need `styled-components@v3` you can install `prev` version:

```bash
npm install styled-normalize@prev
```

https://github.com/sergeysova/styled-normalize/releases/tag/v8.0.4-prev

**Comment by sergeysova** [comment]
Also fixed in #10

**Comment by elektronik2k5** [comment]
Thanks @sergeysova ! I suggest we add this to `README.md`, since right now it isn't clear what should `styled-components@3` users do. Would you like a PR for that?

**Comment by sergeysova** [comment]
If you have some time, please, make PR.

**Comment by elektronik2k5** [comment]
I see it's documented already. Thanks!
